[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#C8FF57"
backgroundColor = "#07080D"
secondaryBackgroundColor = "#0E0F16"
textColor = "#F0F4FF"
font = "sans serif"
